# Generated by Django 2.0 on 2019-07-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='dni',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='identity',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='Identity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'PASSPORT'), ('RESIDENCE', 'RESIDENCE')], default=None, max_length=10, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
