# Generated by Django 2.0 on 2019-06-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='final_date',
            field=models.DateField(null=True, verbose_name='Final date'),
        ),
    ]
