# Generated by Django 2.0 on 2019-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20190701_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='clausule',
            field=models.CharField(choices=[('Services', 'Services'), ('Professional', 'Professional')], default=None, max_length=30, verbose_name='Clausule'),
            preserve_default=False,
        ),
    ]
