# Generated by Django 2.0 on 2019-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190701_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Training Program Name'),
        ),
    ]
