# Generated by Django 2.0 on 2019-07-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190701_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='end_time',
            field=models.DateField(default=None, verbose_name='End time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='enterprise',
            field=models.CharField(default=None, max_length=30, verbose_name='Enterprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='start_time',
            field=models.DateField(default=None, verbose_name='Start time'),
            preserve_default=False,
        ),
    ]
