# Generated by Django 2.0 on 2019-07-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190701_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Nombre de programa de entrenamiento'),
        ),
    ]
