# Generated by Django 2.0 on 2019-07-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190701_0447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'verbose_name': 'Training program', 'verbose_name_plural': 'Training programs'},
        ),
    ]
