# Generated by Django 2.0 on 2019-07-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190701_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'verbose_name': 'Programas de entrenamiento', 'verbose_name_plural': 'Programas de entrenamiento'},
        ),
    ]
