# Generated by Django 2.0 on 2019-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20190701_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='event_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, verbose_name='Event status'),
        ),
    ]
