# Generated by Django 2.0 on 2019-06-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Marriage', 'Marriage'), ('Funeraral', 'Parlor'), ('Judge', 'Judge'), ('Personal', 'Personal')], max_length=10, verbose_name='Type')),
                ('from_data', models.DateField(verbose_name='From data')),
                ('to_data', models.DateField(verbose_name='To data')),
                ('reason', models.CharField(max_length=20, verbose_name='Reason')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10, verbose_name='Status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance request',
                'verbose_name_plural': 'Attendances request',
            },
        ),
    ]
