# Generated by Django 2.0 on 2019-06-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerequest',
            name='from_data',
        ),
        migrations.RemoveField(
            model_name='attendancerequest',
            name='to_data',
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='from_date',
            field=models.DateField(default=None, verbose_name='From date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='to_date',
            field=models.DateField(default=None, verbose_name='To date'),
            preserve_default=False,
        ),
    ]
