# Generated by Django 2.0 on 2019-07-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_auto_20190629_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assistance',
        ),
    ]
