# Generated by Django 2.0 on 2019-06-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
