# Generated by Django 2.0 on 2019-06-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerequest',
            name='explanation',
        ),
    ]
