# Generated by Django 2.0 on 2019-07-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20190717_0036'),
        ('controls', '0003_delete_assistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('mark', models.CharField(choices=[('present', 'Present'), ('Absent', 'Absent'), ('Half day', 'Half day')], max_length=30, verbose_name='Mark')),
                ('employee', models.ManyToManyField(to='employee.Employee', verbose_name='Employees')),
            ],
        ),
    ]
