# Generated by Django 2.0 on 2019-07-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_assistance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistance',
            options={'verbose_name': 'Assistance', 'verbose_name_plural': 'Assitances'},
        ),
    ]
