# Generated by Django 2.1 on 2019-04-24 05:50

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, unique=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, unique=True, verbose_name='Last name')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1, verbose_name='Gender')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('civil_status', models.CharField(choices=[('a', 'Alone'), ('ad', 'Adjoined'), ('ma', 'Married'), ('d', 'Divorced')], max_length=2, verbose_name='Civil status')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
            ],
        ),
    ]
