# Generated by Django 2.0 on 2019-06-29 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type', models.CharField(choices=[('Primary school', 'Primary'), ('High school', 'High school'), ('University', 'University'), ('Bachelor degree', 'Bachelor degree'), ('Master degree', 'Master degree'), ('Doctor degree', 'Doctor degree'), ('Post doctor degree', 'Post doctor degree'), ('Professional school', 'Professional school'), ('No study', 'No study')], max_length=20, verbose_name='Study type')),
                ('grade', models.CharField(choices=[('B.S', 'B.S'), ('B.A', 'B.A'), ('M.S', 'M.S'), ('M.A', 'M.A'), ('Ph.D.', 'Ph.D.'), ('MBA', 'MBA'), ('JD', 'JD'), ('MD', 'MD')], max_length=6, verbose_name='Grade')),
                ('description', models.CharField(blank=True, default=False, max_length=200, verbose_name='Description')),
                ('from_date', models.DateField(verbose_name='From date')),
                ('to_date', models.DateField(null=True, verbose_name='To date')),
                ('institute', models.CharField(default=False, max_length=30, verbose_name='Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1, verbose_name='Gender')),
                ('identity', models.CharField(max_length=30, unique=True, verbose_name='Identity')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('civil_status', models.CharField(choices=[('a', 'Alone'), ('ma', 'Married'), ('d', 'Divorced')], max_length=2, verbose_name='Civil status')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('email', models.EmailField(default=False, max_length=70, verbose_name='Email')),
                ('nationality', models.CharField(blank=True, max_length=20, verbose_name='Nationality')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1, verbose_name='Gender')),
                ('identity', models.CharField(db_index=True, max_length=30, verbose_name='Identity')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('civil_status', models.CharField(choices=[('a', 'Alone'), ('ma', 'Married'), ('d', 'Divorced')], max_length=2, verbose_name='Civil status')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('email', models.EmailField(default=False, max_length=70, verbose_name='Email')),
                ('nationality', models.CharField(blank=True, max_length=20, verbose_name='Nationality')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Employee',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='academicstudies',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee'),
        ),
    ]
