# Generated by Django 2.0 on 2019-06-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'PASSPORT'), ('RESIDENCE', 'RESIDENCE')], default=False, max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'PASSPORT'), ('RESIDENCE', 'RESIDENCE')], default=False, max_length=10, verbose_name='Type'),
        ),
    ]
