# Generated by Django 2.0 on 2019-05-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190503_1654'),
        ('employee', '0003_auto_20190506_1705'),
    ]

    operations = [
    ]
