# Generated by Django 2.0 on 2019-05-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_merge_20190506_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(choices=[('a', 'Alone'), ('ma', 'Married'), ('d', 'Divorced')], max_length=2, verbose_name='Civil status'),
        ),
    ]
