# Generated by Django 2.0 on 2019-07-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20190629_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicstudies',
            options={'verbose_name': 'Academic studie', 'verbose_name_plural': 'Academic studies'},
        ),
    ]
