# Generated by Django 2.0 on 2019-07-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20190701_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicstudies',
            name='institute',
        ),
        migrations.AddField(
            model_name='academicstudies',
            name='place',
            field=models.CharField(default=None, max_length=70, verbose_name='Place'),
            preserve_default=False,
        ),
    ]
