# Generated by Django 2.0 on 2019-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20190614_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='nationality',
        ),
        migrations.AddField(
            model_name='employee',
            name='naturalized',
            field=models.BooleanField(default=False, verbose_name='Nationalized'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='naturalized',
            field=models.BooleanField(default=False, verbose_name='Nationalized'),
        ),
    ]
