# Generated by Django 2.0 on 2019-07-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20190701_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstudies',
            name='from_date',
            field=models.DateField(verbose_name='Desde'),
        ),
        migrations.AlterField(
            model_name='academicstudies',
            name='to_date',
            field=models.DateField(null=True, verbose_name='Hasta'),
        ),
    ]
