# Generated by Django 2.0 on 2019-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20190614_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='naturalized',
            field=models.BooleanField(default=False, verbose_name='Naturalized'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='naturalized',
            field=models.BooleanField(default=False, verbose_name='Naturalized'),
        ),
    ]
