# Generated by Django 2.0 on 2019-07-17 06:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20190710_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=1, verbose_name='Gender')),
                ('identity', models.CharField(max_length=30, unique=True, verbose_name='Identity')),
                ('type', models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'PASSPORT'), ('RESIDENCE', 'RESIDENCE')], max_length=10, verbose_name='Type')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('civil_status', models.CharField(choices=[('a', 'Alone'), ('ma', 'Married'), ('d', 'Divorced')], max_length=2, verbose_name='Civil status')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone')),
                ('nationality', models.CharField(blank=True, max_length=20, verbose_name='Nationality')),
            ],
        ),
    ]
