# Generated by Django 2.0 on 2019-07-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=70, verbose_name='Place')),
            ],
        ),
        migrations.RenameModel(
            old_name='Family',
            new_name='Relative',
        ),
        migrations.AlterModelOptions(
            name='relative',
            options={'verbose_name': 'Relative', 'verbose_name_plural': 'Relatives'},
        ),
    ]
