# Generated by Django 2.0 on 2019-07-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20190717_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academies',
            options={'verbose_name': 'Academy', 'verbose_name_plural': 'Academies'},
        ),
    ]
