# Generated by Django 2.0 on 2019-07-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20190717_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalemployee',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='academicstudies',
            name='place',
        ),
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
    ]
