# Generated by Django 2.0 on 2019-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_vacationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
