# Generated by Django 2.0 on 2019-07-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0003_auto_20190701_0457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'verbose_name': 'Vacation request', 'verbose_name_plural': 'Vacations request'},
        ),
    ]
