# Generated by Django 2.0 on 2019-07-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_auto_20190710_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsuranceapplication',
            name='offer_date',
        ),
    ]
