# Generated by Django 2.0 on 2019-05-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='employee',
        ),
    ]
