# Generated by Django 2.0 on 2019-05-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190425_1302'),
        ('charge', '0002_remove_charge_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=20, verbose_name='Detail')),
                ('initial_date', models.DateField(verbose_name='Initial date')),
                ('final_date', models.DateField(verbose_name='Final date')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charge.Charge', verbose_name='charge')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
