# Generated by Django 2.0 on 2019-05-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='charge',
        ),
    ]
