# Generated by Django 2.0 on 2019-05-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0004_remove_history_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='employee',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
