# Generated by Django 2.0 on 2019-06-04 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_historicalemployee'),
        ('charge', '0005_auto_20190519_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(verbose_name='Initial date')),
                ('final_date', models.DateField(verbose_name='Final date')),
                ('motive_movement', models.CharField(max_length=300, verbose_name='Motive of movement')),
                ('authorized_for', models.CharField(max_length=20, verbose_name='Authorized for')),
                ('status', models.CharField(choices=[(('Active',), 'Active'), ('Inactive', 'Inactive')], max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Charge history',
                'verbose_name_plural': 'Charges history',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='name',
            field=models.CharField(default=None, max_length=20, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[(('Active',), 'Active'), ('Inactive', 'Inactive')], default=None, max_length=10, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargehistory',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charge.Charge', verbose_name='Charge'),
        ),
        migrations.AddField(
            model_name='chargehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='charge',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.Department', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
