# Generated by Django 2.0 on 2019-06-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0006_auto_20190603_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargehistory',
            options={'verbose_name': 'ChargeHistory', 'verbose_name_plural': 'ChargesHistory'},
        ),
    ]
