# Generated by Django 2.0 on 2019-06-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0008_auto_20190604_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='payment',
            field=models.IntegerField(default=0, verbose_name='Payment'),
            preserve_default=False,
        ),
    ]
