# Generated by Django 2.0 on 2019-06-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0010_auto_20190610_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
