# Generated by Django 2.0 on 2019-06-14 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0013_auto_20190614_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='payment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(6000), django.core.validators.MaxValueValidator(50000)], verbose_name='Payment'),
        ),
    ]
